services:
  mysql:
    container_name: 'users-crud-mysql'
    image: 'mysql:8.0.36'
    environment:
      - 'MYSQL_DATABASE=users_crud'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local